### ISSUE TITLE
dev_perf and instruction_score unpack error

### ISSUE THREAD

**Issue by ChillingDream** [Lichang-Chen/InstructZero#2]
I got a unpack error at run_instructzero.py Line187, where the sorted functions return two lists. So, XXX.sorted()[1][0] is a float number and cannot be unpacked.
So how do I fix this? Could you elaborate the meaning of dev_pef and instruction_score.

**Comment by Lichang-Chen** [comment]
Dev_perf is the performance on the development set and the instruction score means the score for the specific instruction. If your API model is "ChatGPT, " it shouldn't have the bug. We will fix the function for other API Models like LlaMA and FLAN-T5 in the following days.
