### ISSUE TITLE
Questions about code and cma-es

### ISSUE THREAD

**Issue by xiaoyuxin1002** [Lichang-Chen/InstructZero#3]
Thanks for this interesting paper! I met some problems while reproducing the results.
1. In Line 305 of run_instructzero.py, should you flatten y_train before argsort? Otherwise, the starting idxs will always consist of [0] only? I don’t quite understand this line. Could you please explain it a little bit? Thanks!
2. I am having some issues with the cma-es optimizer. In particular, my es.best.f is always 0 in Line 62 in instruction_coupled_kernel.py. Do you know what could be the potential reasons?
3. Besides the best instructions listed in your paper's Table 2, would you mind also sharing other generated prompts and their scores during your tuning process? Thanks!

**Comment by Lichang-Chen** [comment]
1. for this question, please refer to our latest code. We've already solved it.
2. if your es.best.f is always 0, it means the evaluations are always failed. ( It may happen when your API LLM is open-sourced models, e.g., WizardLM. You may need to change the hyperparameters to make it work. )
3. We will release more results when we update our paper on Arxiv. Stay tuned!

**Comment by xiaoyuxin1002** [comment]
Thank you very much!
2. I indeed used open-sourced models for the API LLM when my es.best.f was always 0. Could you please explain why the evaluations using open-sourced models are always failed and what hyperparameters I need to change?

**Comment by Lichang-Chen** [comment]
Open-source LLMs always fail in the evaluation because they do not have the solid instruction-following capacity as the API LLM, e.g., ChatGPT, Claude, etc.
